Use WARN for EOFError
We hit an EOFError that happens frequently, and before we could fix that, use WARN instead of ERROR to improve user experience using our collector.

The specific EOFError was:

EOFError: end of file reached
lib/ruby/3.0.0/openssl/buffering.rb:148:in `sysread'
lib/ruby/3.0.0/openssl/buffering.rb:148:in `readpartial'
rspec-buildkite-analytics/lib/buildkite/collector/socket_connection.rb:73:in `block in initialize'